# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'EnxUIKitDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
       pod 'Socket.IO-Client-Swift', '~> 16.1.1'
        pod 'ReachabilitySwift'
        pod 'AlertToast'

  # Pods for EnxUIKitDemoApp
  


end
